### PR TITLE
Add dropdown to change time zone

### PR DESCRIPTION
**Pull request by slahrichi**

### CODE REVIEW

**Comment by szhu** [comment]
Will do soon, thanks for creating this issue!

**Comment by szhu** [comment]
I hope to get the dropdown setting to you soon, but I don't want to delay you being able to use this extension for your timezone.

To manually change the timezone, you can go into the downloaded code and manually edit the line here: https://github.com/szhu/BeNotified/blob/1719b26/src/background.js#L90

You can change it to one of the following values from https://bereal.devin.fun/:
- `us-central` (current value)
- `europe-west`
- `asia-east`
- `asia-west`

**Comment by szhu** [comment]
Oh, I misread, this is a PR and not an issue… wow thank you!

**Review by szhu — COMMENTED** [review]
@slahrichi I updated this PR to match the code style of the rest of the codebase. 

In case you need it in the future, here is a link to the previous version of your PR: https://github.com/szhu/BeNotified/commits/266202b38ccb41270ea2bf43b695c65d8fc0c8c3

When you can, please do the following:
- Take a look at the updated PR (and try out the updated code if you can) and let me know if you find any issues.
- I currently don't have a license listed in the repo, but I am considering adding one in the future. Can you confirm whether you would be okay if in the future I added an open source license of my choice from https://opensource.org/licenses and had it apply to everyone's contributions to this repo, including yours?

Thanks so much again, excited to merge this.

**Comment by slahrichi** [comment]
Hi @szhu! This looks great, thank you! I added the updated extension and will test if I get the notification tomorrow. As for the license, feel free to use whichever one you want. Happy merging!

**Comment by szhu** [comment]
@slahrichi I was able to test out that this feature is working properly today, as I happen to be currently traveling in a non-Americas time zone. Thanks for your contributing this feature! Now I can actually use this extension for the rest of my trip :)

**Pull request merged**
